# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build jj reset'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["settings_reset"]'
      kconfig: '["CONFIG_ZMK_POINTING=y\nCONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y\nCONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=16"]'
      alphas: '["qwerty"]'
